server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.175.146:3306/tensquare_qa?characterEncoding=utf-8&useSSL=false
    username: root
    password: root105752
  jpa: 
    database: MySQL
    show-sql: true
